version: '3'
services:
  postgres:
    container_name: postgres
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"